<a href="https://colab.research.google.com/github/Arjun-P-Dinesh/QuantumComputing/blob/main/Arjun_503_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install qiskit
!pip install qiskit-aer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 78.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.4/119.4 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 57.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 MB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.5/108.5 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 17.5 MB/s eta 0:00:00


In [1]:
#tensor product of 2 states
import numpy as np
#define the identity matrix and NOT gate also known to be as pauli-X gate
I = np.array([[1,0],[0,1]])
X = np.array([[0,1],[1,0]])

def tensor_product(a,b):
    return np.kron(a,b)

tensor_product(I,X)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

the tenser product in mathematics lets consider two vector spaces A and B and its tensor product is A ⊗ B where A and B is a vector space to which it has a bilinear mapping A X B -> A ⊗ B that maps a pair (a,b) where a∈A and b∈B

now when it comes to states we call it kronecker prduct an operation on two matrices resulting in a block matrices


In [2]:
# Tensor Product of two quantum states (Krodnecker Gate)
#implementing Control unitary operation c(x)
# Define the Identity matrix and Pauli-X gate
I = np.array([[1, 0],[0, 1]])

X = np.array([[0, 1],[1, 0]])

# Define the projector |0><0| and |1><1|
projection_0 = np.array([[1, 0],[0, 0]])

projection_1 = np.array([[0, 0],[0, 1]])

# Calculate the controlled unitary operation C(x)
C_x = np.kron(projection_0, I) + np.kron(projection_1, X)

# Display the result
print("Controlled unitary operation C(x):")
print(C_x)

Controlled unitary operation C(x):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [4]:
#implementation of tensor product of any two vectors
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])


def tensor_product(a,b):
    return np.kron(a,b)

tensor_product(a,b)

array([ 4,  5,  6,  8, 10, 12, 12, 15, 18])

In [5]:
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector, Operator, DensityMatrix,partial_trace
from qiskit.visualization import plot_histogram
from qiskit_aer import Aer

In [6]:
#define the quantum states
psi_0 = ((1/np.sqrt(2))*np.array([1,1]))
psi_1 = ((1/np.sqrt(2))*np.array([1,-1]))

#defining the pauli X
X = np.array([[0,1],[1,0]])

#implement the tensor product of two states
state=np.kron(psi_0,psi_1)
print(state)

[ 0.5 -0.5  0.5 -0.5]


In [7]:
# Apply the Pauli-X operator to the first qubit
I=np.array([[1,0],[0,1]])
operator=np.kron(X,I)
print(operator)

[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]


In [8]:
new_state=np.dot(operator,state)
print(new_state)

[ 0.5 -0.5  0.5 -0.5]


In [9]:
# Step 4: Simulate a partial measurement
def sim(state):
   probabilities = np.abs(state)**2  # Probability distribution
   measurement_outcome = np.random.choice(range(len(state)), p=probabilities)
   return measurement_outcome

# Perform a partial measurement on the state
measurement_result = sim(new_state)
print("Measurement result (index of the qubit):", measurement_result)

Measurement result (index of the qubit): 1
